import { createContext, useContext, useMemo, useState, type ReactNode, type FormEvent, type ButtonHTMLAttributes } from 'react';
import { QueryClient, QueryClientProvider, useQueryClient } from '@tanstack/react-query';
import { ErrorBoundary } from '@/components/error-boundary';
import { Toaster } from '@/components/ui/toaster';
import { TooltipProvider } from '@/components/ui/tooltip';
import NotFound from '@/pages/not-found';
import { Route, Switch, useLocation, Router as WouterRouter, Link } from 'wouter';
import {
  Activity, ArrowDownRight, ArrowLeft, ArrowRight, BadgeCheck, Check, CircleHelp, Clock3,
  Coins, FileCheck2, Gauge, HeartHandshake, Leaf, LockKeyhole, Menu, Monitor, PackageCheck,
  Recycle, ScanLine, ShieldCheck, Smartphone, Sparkles, Trash2, Upload, UserRound,
} from 'lucide-react';
import {
  DeviceCategory, Condition, DeviceInputSource, Route as EcoRoute,
  useHealthCheck, getHealthCheckQueryKey, useGetEcoCycleDashboard, getGetEcoCycleDashboardQueryKey,
  useListEcoCycleDevices, getListEcoCycleDevicesQueryKey, useCreateEcoCycleDevice, useDeleteEcoCycleDevice,
  useIdentifyEcoCycleDevice, useRunEcoCycleDiagnostics, useCalculateEcoCycleValuation,
  useStartEcoCycleSanitization, useListEcoCycleCertificates, getListEcoCycleCertificatesQueryKey,
  useCreateEcoCycleCertificate, useEvaluateEcoCycleRouting, useListEcoCyclePartners,
  getListEcoCyclePartnersQueryKey, useGetEcoCycleCredits, getGetEcoCycleCreditsQueryKey,
  useGetEcoCycleImpact, getGetEcoCycleImpactQueryKey, useListEcoCycleHistory,
  getListEcoCycleHistoryQueryKey,
} from '@workspace/api-client-react';
import type { DeviceInput, Device, DiagnosticResult, Valuation, SanitizationRecord, RoutingResult } from '@workspace/api-client-react';

const queryClient = new QueryClient();
type Workflow = { device: DeviceInput | null; saved?: Device; diagnostics?: DiagnosticResult; value?: Valuation; sanitation?: SanitizationRecord; routing?: RoutingResult };
const FlowContext = createContext<{ flow: Workflow; setFlow: (flow: Workflow) => void; device: DeviceInput; setDevice: (d: DeviceInput) => void }>({
  flow: { device: null }, setFlow: () => {}, device: blankDevice(), setDevice: () => {},
});
function blankDevice(): DeviceInput {
  return { category: DeviceCategory.Smartphone, brand: '', model: '', condition: Condition.WORKING, powersOn: true, hasPersonalData: true, source: DeviceInputSource.USER_REPORTED, location: 'Bengaluru' };
}
const navGroups = [
  { title: 'YOUR CIRCULAR JOURNEY', links: [
    ['Dashboard', '/dashboard', Gauge], ['Scan a device', '/scan', ScanLine], ['Diagnostics', '/diagnostics', Activity],
    ['Valuation', '/valuation', Coins], ['Data protection', '/sanitization', LockKeyhole], ['Recommendation', '/results', ArrowRight],
  ] },
  { title: 'DISCOVER & TRACK', links: [
    ['Find a partner', '/matchmaker', HeartHandshake], ['My impact', '/impact', Leaf], ['Certificates', '/certificates', FileCheck2], ['History', '/history', Clock3],
  ] },
];
function Mark({ small = false }: { small?: boolean }) {
  return <div className="logo-mark" style={{ width: small ? 36 : 42, height: small ? 36 : 42, borderRadius: 14, display: 'grid', placeItems: 'center', color: '#193d32', background: '#d4e29b' }}><Recycle size={small ? 20 : 23} strokeWidth={2.4} /></div>;
}
function Shell({ children }: { children: ReactNode }) {
  const [loc] = useLocation();
  return <div className="app-shell">
    <aside className="sidebar">
      <Link href="/dashboard" className="flex items-center gap-3 mb-10"><Mark /><span className="brand-name"><b style={{ display:'block',fontSize:15,letterSpacing:'-.04em' }}>EcoCycle<span style={{color:'#d4e29b'}}> AI</span></b><span style={{fontSize:9,color:'rgba(246,244,226,.48)',letterSpacing:'.13em'}}>A BETTER NEXT LIFE</span></span></Link>
      {navGroups.map(group => <div key={group.title} style={{ marginBottom: 27 }}>
        <div className="nav-group-label eyebrow" style={{ color: 'rgba(246,244,226,.4)', margin: '0 12px 10px', fontSize: 9 }}>{group.title}</div>
        {group.links.map(([name, href, Icon]) => <Link key={href as string} href={href as string} className={`nav-link ${loc === href ? 'active' : ''}`} data-testid={`link-${String(name).toLowerCase().replaceAll(' ','-')}`}><Icon size={17}/><span className="nav-label">{name as string}</span></Link>)}
      </div>)}
      <div style={{ marginTop: 'auto' }}>
        <Link href="/profile" className={`nav-link ${loc === '/profile' ? 'active' : ''}`} data-testid="link-profile"><UserRound size={17}/><span className="nav-label">Profile & settings</span></Link>
        <div className="sidebar-copy" style={{ margin: '20px 12px 0', fontSize: 10, lineHeight: 1.7, color: 'rgba(246,244,226,.42)' }}>A mindful route for every device.<br/>Demo experience · India</div>
      </div>
    </aside>
    <main className="main-area">
      <header className="topbar">
        <div className="eyebrow" style={{ display:'flex',alignItems:'center',gap:8 }}><span style={{ width:7,height:7,borderRadius:99,background:'#95aa62' }} /> DEMO EXPERIENCE <span style={{opacity:.45}}>·</span> INDIA</div>
        <div className="flex items-center gap-3"><HealthStatus/><Link href="/profile" aria-label="Profile settings" data-testid="link-profile-top" style={{ width:38,height:38,borderRadius:99,background:'#e7e8d7',display:'grid',placeItems:'center',color:'#284b3f' }}><UserRound size={17}/></Link></div>
      </header>
      {children}
    </main>
    <nav className="mobile-nav">{[['Home','/dashboard',Gauge],['Scan','/scan',ScanLine],['Value','/valuation',Coins],['Impact','/impact',Leaf],['More','/profile',Menu]].map(([n,h,I]) => <Link key={h as string} href={h as string} className={loc === h ? 'active' : ''} data-testid={`mobile-${String(n).toLowerCase()}`}><I size={20}/><span>{n as string}</span></Link>)}</nav>
  </div>;
}
function PageHead({ kicker, title, desc, action }: { kicker: string; title: string; desc?: string; action?: ReactNode }) {
  return <div className="flex items-end justify-between gap-4 mb-8 anim-in"><div><div className="eyebrow">{kicker}</div><h1 className="page-title">{title}</h1>{desc && <p style={{color:'hsl(var(--muted-foreground))',maxWidth:650,fontSize:14,lineHeight:1.7,margin:0}}>{desc}</p>}</div>{action}</div>;
}
function SourceTag({ children = 'USER REPORTED' }: { children?: ReactNode }) { return <span className="badge outline" style={{fontFamily:'var(--app-font-mono)',fontSize:9,letterSpacing:'.03em'}}>{children}</span>; }
function Notice({ children, tone = 'green' }: { children: ReactNode; tone?: string }) {
  return <div style={{ borderRadius:13, padding:'13px 15px', background:tone==='coral'?'hsl(17 66% 58% / .11)':'hsl(76 42% 86% / .44)', border:'1px solid '+(tone==='coral'?'hsl(17 50% 75%)':'hsl(76 25% 75%)'),fontSize:12,lineHeight:1.6 }}>{children}</div>;
}
function Button({ children, className='', 'data-testid': testId, ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { className?: string; 'data-testid'?: string }) {
  return <button {...props} className={`btn ${className}`} data-testid={testId ?? 'button-action'}>{children}</button>;
}
function Landing() {
  return <div style={{background:'hsl(var(--background))'}}>
    <nav style={{height:76,display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 clamp(20px,6vw,88px)',borderBottom:'1px solid hsl(var(--border))'}}>
      <Link href="/" className="flex items-center gap-3"><Mark/><b style={{fontSize:16,letterSpacing:'-.05em'}}>EcoCycle <span style={{color:'hsl(var(--primary))'}}>AI</span></b></Link>
      <div className="flex items-center gap-3"><Link href="/login" className="btn btn-quiet" data-testid="link-login">Log in</Link><Link href="/register" className="btn btn-primary" data-testid="link-start">Get started <ArrowRight size={16}/></Link></div>
    </nav>
    <section style={{padding:'clamp(58px,9vw,120px) clamp(20px,9vw,140px) 80px',display:'grid',gridTemplateColumns:'1.1fr .9fr',gap:50,alignItems:'center'}} className="landing-hero">
      <div className="anim-in"><div className="badge"><span style={{width:6,height:6,borderRadius:9,background:'#68844e'}}/> THE SECOND LIFE OF THINGS</div>
        <h1 className="serif" style={{fontSize:'clamp(55px,8vw,104px)',lineHeight:.92,letterSpacing:'-.06em',margin:'27px 0 22px',maxWidth:750}}>Your old tech<br/><em style={{color:'hsl(var(--primary))'}}>still has a future.</em></h1>
        <p style={{fontSize:16,lineHeight:1.8,maxWidth:510,color:'hsl(var(--muted-foreground))'}}>Understand what it’s worth, protect what’s yours, and find the right next destination for the electronics you’re ready to let go.</p>
        <div className="flex flex-wrap gap-3 mt-7"><Link href="/scan" className="btn btn-primary" data-testid="link-scan-start">Assess a device <ArrowRight size={17}/></Link><Link href="/dashboard" className="btn btn-quiet" data-testid="link-explore-demo">Explore demo <ArrowDownRight size={17}/></Link></div>
        <div className="flex items-center gap-3 mt-9"><div style={{display:'flex'}}>{['#d6e4a2','#e9aa87','#b5c9b5'].map((c,i)=><span key={c} style={{width:24,height:24,borderRadius:99,border:'2px solid hsl(var(--background))',background:c,marginLeft:i?-7:0}} />)}</div><span style={{fontSize:11,color:'hsl(var(--muted-foreground))'}}>A clearer choice for every device</span></div>
      </div>
      <div className="anim-in delay-2" style={{position:'relative',minHeight:410,display:'grid',placeItems:'center'}}>
        <div style={{position:'absolute',width:'min(100%,440px)',aspectRatio:'1',borderRadius:'49% 51% 48% 52%',background:'#dfe8c8',transform:'rotate(-10deg)'}}/>
        <div style={{position:'relative',width:'min(82%,330px)',height:390,borderRadius:34,background:'#24483e',padding:18,boxShadow:'0 28px 75px rgba(31,57,46,.22)',transform:'rotate(5deg)'}}>
          <div style={{height:'100%',borderRadius:23,background:'linear-gradient(155deg,#e8e9d8 0%,#c5d5ab 100%)',padding:23,display:'flex',flexDirection:'column',justifyContent:'space-between',overflow:'hidden'}}>
            <div className="flex justify-between"><span className="eyebrow">DEVICE JOURNAL · 01</span><ScanLine size={18}/></div>
            <div style={{position:'relative',zIndex:2}}><span className="badge">REPAIRABLE</span><div className="serif" style={{fontSize:38,lineHeight:1,marginTop:15,letterSpacing:'-.04em'}}>Still good<br/>for someone.</div></div>
            <div style={{height:103,borderRadius:15,background:'#294d41',color:'#e4ebce',display:'flex',alignItems:'center',justifyContent:'space-between',padding:'0 17px'}}><div><div className="eyebrow" style={{color:'#a9bd86'}}>ESTIMATED RESALE</div><b className="mono" style={{fontSize:21,display:'block',marginTop:9}}>₹ 12,400</b></div><ArrowUpRightIcon/></div>
          </div>
        </div>
        <div style={{position:'absolute',right:0,bottom:28,padding:'13px 16px',borderRadius:15,background:'hsl(var(--card))',boxShadow:'var(--shadow)',fontSize:11,fontWeight:800,display:'flex',alignItems:'center',gap:9}}><Leaf size={16} color="#496e4e"/> Make the next step count</div>
      </div>
    </section>
    <section style={{padding:'28px clamp(20px,9vw,140px) 84px'}}><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',borderTop:'1px solid hsl(var(--border))',borderBottom:'1px solid hsl(var(--border))'}}>
      {[['01','Know what you have','A guided assessment grounded in your answers, not guesswork dressed as certainty.'],['02','Keep your data yours','Learn the steps before your device leaves your hands.'],['03','Choose a better next step','Resale for working and repairable. Responsible recycling for the rest.']].map(([n,t,d])=><div key={n} style={{padding:'30px 25px 30px 0'}}><div className="eyebrow">{n} / A MORE INFORMED CHOICE</div><h3 style={{fontSize:18,letterSpacing:'-.04em',margin:'14px 0 8px'}}>{t}</h3><p style={{fontSize:12,lineHeight:1.75,color:'hsl(var(--muted-foreground))',maxWidth:300,margin:0}}>{d}</p></div>)}
    </div></section>
    <section style={{margin:'0 clamp(16px,5vw,70px)',padding:'clamp(30px,6vw,75px)',borderRadius:28,background:'hsl(var(--sidebar))',color:'#f1f0dd',display:'grid',gridTemplateColumns:'1fr 1fr',gap:32,alignItems:'center'}}>
      <div><div className="eyebrow" style={{color:'#cbd9a0'}}>THE SIMPLE RULE</div><h2 className="serif" style={{fontSize:'clamp(38px,5vw,62px)',lineHeight:1,letterSpacing:'-.04em',margin:'18px 0 12px'}}>Condition first.<br/>Destination second.</h2><p style={{fontSize:13,lineHeight:1.8,maxWidth:440,color:'rgba(241,240,221,.68)'}}>Value estimates are a starting point, never a guaranteed quote. Your answers are clearly separated from estimates and demo information.</p></div>
      <div style={{display:'grid',gap:12}}>{[['WORKING / REPAIRABLE','RESALE','Keep useful tech in circulation.'],['NON-WORKING / DEAD / SCRAP','RECYCLING','Recover materials through a responsible route.']].map(([a,b,c],i)=><div key={a} style={{display:'flex',alignItems:'center',gap:15,padding:17,borderRadius:16,background:'rgba(255,255,255,.07)',border:'1px solid rgba(255,255,255,.1)'}}><div style={{width:45,height:45,borderRadius:14,background:i?'rgba(232,164,128,.18)':'rgba(212,226,155,.17)',display:'grid',placeItems:'center'}}>{i?<Recycle/>:<HeartHandshake/>}</div><div style={{flex:1}}><div className="eyebrow" style={{color:'#cbd9a0'}}>{a}</div><b style={{fontSize:17,display:'block',margin:'5px 0'}}>{b}</b><span style={{fontSize:11,color:'rgba(241,240,221,.65)'}}>{c}</span></div><ArrowRight size={17}/></div>)}</div>
    </section>
    <section style={{padding:'90px clamp(20px,9vw,140px)',display:'flex',justifyContent:'space-between',alignItems:'center',gap:25,flexWrap:'wrap'}}><div><div className="eyebrow">YOUR NEXT STEP IS SMALL</div><h2 className="serif" style={{fontSize:'clamp(37px,5vw,60px)',letterSpacing:'-.04em',margin:'12px 0'}}>Start with one device.</h2><p style={{color:'hsl(var(--muted-foreground))',fontSize:13}}>No commitment. Just a clearer picture of what comes next.</p></div><Link href="/scan" className="btn btn-primary" data-testid="link-assess-device">Assess your device <ArrowRight size={16}/></Link></section>
    <footer style={{padding:'22px clamp(20px,9vw,140px)',borderTop:'1px solid hsl(var(--border))',display:'flex',justifyContent:'space-between',fontSize:11,color:'hsl(var(--muted-foreground))'}}><span>EcoCycle AI · A considered next step for electronics</span><span>Demo information is clearly marked</span></footer>
    <style>{`@media(max-width:760px){.landing-hero{grid-template-columns:1fr!important;padding-top:54px!important}.landing-hero>div:nth-child(2){min-height:360px!important}.landing-hero>div:nth-child(2)>div:nth-child(2){height:335px!important}.landing-hero>div:nth-child(2)>div:nth-child(2)>div{height:100%!important}section[style*="grid-template-columns:repeat(3"]{grid-template-columns:1fr!important}section[style*="background: hsl(var(--sidebar))"]{grid-template-columns:1fr!important;margin:0 14px!important}}`}</style>
  </div>;
}
function ArrowUpRightIcon(){return <ArrowRight size={18} style={{transform:'rotate(-45deg)'}}/>}
function Dashboard() {
  const q = useGetEcoCycleDashboard({query:{queryKey:getGetEcoCycleDashboardQueryKey()}});
  const {flow} = useContext(FlowContext);
  const summary = q.data;
  return <div className="page-wrap"><PageHead kicker="YOUR DEVICE CIRCULARITY" title="A more thoughtful next step." desc="Your demo overview of devices assessed, responsible routes, and the impact that follows." action={<Link href="/scan" className="btn btn-primary" data-testid="link-new-assessment"><ScanLine size={16}/> Assess a device</Link>}/>
    {q.isLoading ? <LoadingPanel/> : q.isError ? <ErrorPanel onRetry={()=>q.refetch()}/> : <>
    <div className="grid-main anim-in delay-1">
      <div className="panel" style={{padding:26,background:'hsl(var(--sidebar))',color:'#f2f0df',position:'relative',overflow:'hidden'}}>
        <div style={{position:'absolute',right:-18,top:-18,width:150,height:150,borderRadius:'50%',border:'1px solid rgba(212,226,155,.18)'}}/><div style={{position:'absolute',right:10,top:10,width:105,height:105,borderRadius:'50%',border:'1px solid rgba(212,226,155,.16)'}}/>
        <div className="eyebrow" style={{color:'#cbd9a0'}}>YOUR CIRCULAR FOOTPRINT <SourceTag>DEMO DATA</SourceTag></div>
        <div className="serif" style={{fontSize:57,lineHeight:1,letterSpacing:'-.05em',margin:'25px 0 5px'}}>{summary?.co2SavedKg ?? 0}<span style={{fontSize:19,marginLeft:7,color:'#cbd9a0'}}>kg CO₂</span></div><div style={{fontSize:12,color:'rgba(242,240,223,.6)'}}>estimated emissions saved in this demo</div>
        <div style={{display:'flex',gap:25,marginTop:34,paddingTop:19,borderTop:'1px solid rgba(255,255,255,.15)'}}><div><b style={{fontSize:20}}>{summary?.devicesReused ?? 0}</b><div className="eyebrow" style={{color:'rgba(242,240,223,.55)',marginTop:4}}>REUSED</div></div><div><b style={{fontSize:20}}>{summary?.devicesRecycled ?? 0}</b><div className="eyebrow" style={{color:'rgba(242,240,223,.55)',marginTop:4}}>RECYCLED</div></div><div><b style={{fontSize:20}}>{summary?.ecoCredits ?? 0}</b><div className="eyebrow" style={{color:'rgba(242,240,223,.55)',marginTop:4}}>ECO CREDITS</div></div></div>
      </div>
      <div className="rule-box" style={{padding:25,display:'flex',flexDirection:'column',justifyContent:'space-between'}}><div><div className="eyebrow">THE ROUTING RULE</div><h3 className="serif" style={{fontSize:29,lineHeight:1.1,margin:'13px 0'}}>Give each device<br/>the right kind of next.</h3></div><div style={{display:'grid',gap:10}}><div className="flex justify-between items-center"><span style={{fontWeight:800,fontSize:12}}>Working or repairable</span><span className="badge">RESALE</span></div><div className="flex justify-between items-center"><span style={{fontWeight:800,fontSize:12}}>Non-working, dead or scrap</span><span className="badge coral">RECYCLING</span></div></div></div>
    </div>
    <div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:14,margin:'18px 0'}} className="anim-in delay-2">{[{label:'Devices assessed',value:summary?.devicesProcessed??0,Icon:Monitor},{label:'Reused responsibly',value:summary?.devicesReused??0,Icon:HeartHandshake},{label:'Eco credits',value:summary?.ecoCredits??0,Icon:Coins}].map(({label,value,Icon})=><div className="panel stat-card" key={label}><div className="eyebrow">{label}</div><strong>{value}</strong><div className="flex items-center gap-2" style={{fontSize:11,color:'hsl(var(--muted-foreground))'}}><Icon size={14}/> Demo summary</div></div>)}</div>
    <div className="grid-main anim-in delay-3"><div className="panel" style={{padding:22}}><div className="flex justify-between items-center mb-5"><h3 style={{fontSize:16,margin:0}}>Recent assessments</h3><Link href="/history" style={{fontSize:11,fontWeight:800,color:'hsl(var(--primary))'}}>View history →</Link></div>
      {flow.saved && <Notice>Current local journey: <b>{flow.saved.brand} {flow.saved.model}</b> · {flow.saved.condition} <SourceTag>{flow.saved.source}</SourceTag></Notice>}
      {(summary?.recentAssessments ?? []).length ? <div style={{marginTop:16}}>{summary?.recentAssessments.slice(0,4).map(a=><div key={a.id} className="flex items-center gap-3" style={{padding:'12px 0',borderTop:'1px solid hsl(var(--border))'}}><div style={{width:38,height:38,borderRadius:12,background:'hsl(var(--secondary))',display:'grid',placeItems:'center'}}><Smartphone size={18}/></div><div style={{flex:1}}><b style={{fontSize:12}}>{a.deviceName}</b><div style={{fontSize:10,color:'hsl(var(--muted-foreground))',marginTop:4}}>{a.condition} · {a.route} · {a.source}</div></div><span className="mono" style={{fontSize:12}}>₹{a.value.toLocaleString('en-IN')}</span></div>)}</div> : <EmptyBlock title="Your first assessment goes here" detail="Scan an old device to see its recommendation here." action={<Link href="/scan" className="btn btn-soft" data-testid="link-first-assessment">Start an assessment <ArrowRight size={15}/></Link>}/>}
      </div><div className="panel" style={{padding:22}}><div className="eyebrow">PICK UP WHERE YOU LEFT OFF</div><h3 className="serif" style={{fontSize:27,lineHeight:1.12,margin:'14px 0'}}>See the full picture,<br/>not just a price.</h3><p style={{fontSize:12,lineHeight:1.7,color:'hsl(var(--muted-foreground))'}}>Assess condition, understand possible value, prepare your data, and choose a destination with confidence.</p><Link href={flow.saved?'/results':'/scan'} className="btn btn-primary" style={{marginTop:10}} data-testid="link-continue">{flow.saved?'Continue your journey':'Start with a device'} <ArrowRight size={16}/></Link></div></div>
    </>}
  </div>;
}
function LoadingPanel(){return <div className="panel" style={{padding:25}}><div style={{height:18,width:'34%',borderRadius:8,background:'hsl(var(--muted))'}}/><div style={{height:90,marginTop:20,borderRadius:14,background:'hsl(var(--muted))',opacity:.55}}/><p className="eyebrow" style={{marginTop:17}}>Loading the demo overview…</p></div>}
function ErrorPanel({onRetry}:{onRetry:()=>void}){return <div className="panel" style={{padding:28,textAlign:'center'}}><CircleHelp size={28} color="hsl(var(--accent))"/><h3>We couldn’t load this just now</h3><p style={{fontSize:13,color:'hsl(var(--muted-foreground))'}}>Your current assessment stays on this device. Try the demo summary again.</p><Button onClick={onRetry} className="btn-primary">Try again</Button></div>}
function EmptyBlock({title,detail,action}:{title:string;detail:string;action?:ReactNode}){return <div style={{textAlign:'center',padding:'30px 18px'}}><div style={{width:48,height:48,borderRadius:16,background:'hsl(var(--secondary))',display:'grid',placeItems:'center',margin:'0 auto 14px',color:'hsl(var(--primary))'}}><PackageCheck size={22}/></div><b style={{fontSize:13}}>{title}</b><p style={{fontSize:11,color:'hsl(var(--muted-foreground))',lineHeight:1.65}}>{detail}</p>{action}</div>}
function ScanPage(){
  const ctx=useContext(FlowContext); const {device,setDevice,setFlow,flow}=ctx;
  const identify=useIdentifyEcoCycleDevice(); const create=useCreateEcoCycleDevice();
  const [file,setFile]=useState<File|null>(null); const [camera,setCamera]=useState(''); const [identified,setIdentified]=useState(false); const [error,setError]=useState('');
  const update=(key:keyof DeviceInput,value:unknown)=>setDevice({...device,[key]:value});
  const doIdentify=()=>{setError('');identify.mutate({data:{category:device.category,description:`${device.brand||'Unspecified brand'} ${device.model||device.category}`,imageName:file?.name,imageSize:file?.size}},{onSuccess:()=>setIdentified(true),onError:()=>setError('Identification could not complete. Continue by entering the device details yourself.')});};
  const confirm=()=>{create.mutate({data:{...device}},{onSuccess:saved=>{setFlow({...flow,device:{...device},saved});setIdentified(true)},onError:()=>{setFlow({...flow,device:{...device}});setError('Could not save to the demo service. Your entered details are still available in this journey.')}})};
  const requestCamera=async()=>{if(!navigator.mediaDevices?.getUserMedia){setCamera('Camera permission is unavailable in this browser. Upload an image or choose a category instead.');return} try{const stream=await navigator.mediaDevices.getUserMedia({video:true});stream.getTracks().forEach(t=>t.stop());setCamera('Camera permission granted. Capture is not required for this demo; you can upload an image or continue with details.')}catch{setCamera('Camera permission was not granted. You can continue with image upload or category selection.')}};
  return <div className="page-wrap"><PageHead kicker="STEP 01 · IDENTIFY" title="Let’s meet your device." desc="Add a photo or choose a category. Identification is an estimate; you’ll confirm the details before assessment."/>
    <div className="grid-main"><div className="panel" style={{padding:24}}>
      <div className="scan-drop" style={{borderRadius:18,padding:26,textAlign:'center'}}><div style={{width:55,height:55,borderRadius:18,background:'hsl(var(--secondary))',display:'grid',placeItems:'center',margin:'0 auto 13px'}}><ScanLine size={24}/></div><b style={{fontSize:14}}>Add a device photo</b><p style={{fontSize:11,color:'hsl(var(--muted-foreground))'}}>An image can help identify the make and model.</p><div className="flex justify-center flex-wrap gap-2"><label className="btn btn-soft" style={{cursor:'pointer'}}><Upload size={15}/> Upload image<input data-testid="input-device-image" type="file" accept="image/*" hidden onChange={e=>setFile(e.target.files?.[0]??null)}/></label><Button onClick={requestCamera} className="btn-quiet"><ScanLine size={15}/> Request camera access</Button></div>{file&&<div className="badge" style={{marginTop:13}}>{file.name} · {Math.round(file.size/1024)} KB</div>}</div>
      {camera&&<p style={{fontSize:11,lineHeight:1.6,marginTop:12}} role="status">{camera}</p>}
      <button onClick={doIdentify} className="btn btn-primary" disabled={identify.isPending} data-testid="button-identify" style={{width:'100%',marginTop:17}}>{identify.isPending?<span>Identifying…</span>:<><Sparkles size={16}/> Identify from my evidence</>}</button>
      {identify.data&&<Notice><b>{identify.data.brand} {identify.data.model}</b> · estimated {identify.data.estimatedYear||'year unavailable'} · {Math.round(identify.data.confidence*100)}% confidence <SourceTag>{identify.data.source}</SourceTag><div style={{marginTop:8}}>{identify.data.evidence.join(' · ')}</div></Notice>}
      {error&&<Notice tone="coral">{error}</Notice>}
      <div style={{borderTop:'1px solid hsl(var(--border))',marginTop:23,paddingTop:20}}><div className="eyebrow">OR CHOOSE A CATEGORY</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:8,marginTop:12}}>{Object.values(DeviceCategory).slice(0,9).map(c=><button key={c} onClick={()=>{update('category',c);setIdentified(false)}} data-testid={`category-${c.toLowerCase().replaceAll(' ','-')}`} className="btn btn-quiet" style={{padding:'10px 6px',minHeight:44,borderRadius:12,fontSize:10,borderColor:device.category===c?'hsl(var(--primary))':undefined,background:device.category===c?'hsl(var(--secondary))':undefined}}>{c}</button>)}</div></div>
    </div><div className="panel" style={{padding:24}}><div className="flex justify-between items-center"><div><div className="eyebrow">CONFIRM WHAT YOU KNOW</div><h3 style={{fontSize:17,margin:'7px 0 18px'}}>Device details</h3></div><SourceTag/></div>
      <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}><label><span className="label">Category</span><select className="field" value={device.category} onChange={e=>update('category',e.target.value)}>{Object.values(DeviceCategory).map(c=><option key={c}>{c}</option>)}</select></label><label><span className="label">Brand</span><input className="field" value={device.brand||''} onChange={e=>update('brand',e.target.value)} placeholder="e.g. Samsung"/></label><label><span className="label">Model</span><input className="field" value={device.model||''} onChange={e=>update('model',e.target.value)} placeholder="Model name"/></label><label><span className="label">Purchase year</span><input className="field" type="number" value={device.purchaseYear||''} onChange={e=>update('purchaseYear',Number(e.target.value))} placeholder="2020"/></label><label><span className="label">Storage</span><input className="field" value={device.storage||''} onChange={e=>update('storage',e.target.value)} placeholder="128 GB"/></label><label><span className="label">Location</span><input className="field" value={device.location||''} onChange={e=>update('location',e.target.value)} placeholder="City"/></label></div>
      {identified&&identify.data&&<Notice><b>Please confirm the identification.</b> The suggested make, model and year are AI-estimated, not device-verified.</Notice>}
      <div style={{marginTop:17}}><Button onClick={confirm} disabled={create.isPending} className="btn-primary" style={{width:'100%'}} data-testid="button-confirm-device">{create.isPending?'Saving assessment…':'Confirm device & continue'} <ArrowRight size={15}/></Button></div>
      <p style={{fontSize:10,color:'hsl(var(--muted-foreground))',lineHeight:1.6}}>Saving creates a demo-backed assessment record. Your answers remain user-reported.</p>
    </div></div>
  </div>;
}
function DemoJourneys(){const{setDevice,setFlow}=useContext(FlowContext);const[,go]=useLocation();
 const start=(kind:'phone'|'laptop')=>{const d:DeviceInput=kind==='phone'?{...blankDevice(),category:DeviceCategory.Smartphone,brand:'Samsung',model:'Galaxy S21',generation:'2021',purchaseYear:2021,storage:'128 GB',condition:Condition.REPAIRABLE,powersOn:true,batteryHealth:76,screenCondition:'Intact',physicalDamage:'Minor wear',source:DeviceInputSource.DEMO_DATA}:{...blankDevice(),category:DeviceCategory.Laptop,brand:'Lenovo',model:'ThinkPad T480',generation:'2018',purchaseYear:2018,storage:'256 GB SSD',ram:'8 GB',condition:Condition.DEAD,powersOn:false,physicalDamage:'No visible damage',source:DeviceInputSource.DEMO_DATA};setDevice(d);setFlow({device:d});go('/diagnostics')};
 return <div className="panel" style={{padding:23}}><div className="eyebrow">TWO COMPLETE DEMO JOURNEYS</div><h3 className="serif" style={{fontSize:25,margin:'9px 0 14px'}}>Explore both outcomes</h3><div style={{display:'grid',gap:10}}><button onClick={()=>start('phone')} className="btn btn-quiet" data-testid="journey-repairable-phone" style={{height:'auto',justifyContent:'space-between',borderRadius:15,padding:14,textAlign:'left'}}><span><b>Repairable smartphone</b><small style={{display:'block',fontSize:10,color:'hsl(var(--muted-foreground))',marginTop:4}}>Samsung Galaxy S21 · resale recommendation</small></span><ArrowRight size={17}/></button><button onClick={()=>start('laptop')} className="btn btn-quiet" data-testid="journey-dead-laptop" style={{height:'auto',justifyContent:'space-between',borderRadius:15,padding:14,textAlign:'left'}}><span><b>Dead laptop</b><small style={{display:'block',fontSize:10,color:'hsl(var(--muted-foreground))',marginTop:4}}>Lenovo ThinkPad T480 · recycling recommendation</small></span><ArrowRight size={17}/></button></div><p style={{fontSize:10,color:'hsl(var(--muted-foreground))',lineHeight:1.6}}>Clearly labeled demo records. Choosing one starts the same assessment steps; no real device is accessed.</p></div>}
function useCurrentDevice(){const {flow,device}=useContext(FlowContext);return flow.device??device}
function Diagnostics(){
 const{flow,setFlow}=useContext(FlowContext);const device=useCurrentDevice();const run=useRunEcoCycleDiagnostics();
 const start=()=>run.mutate({data:{device}},{onSuccess:r=>setFlow({...flow,device,diagnostics:r}),onError:()=>setFlow({...flow,device,diagnostics:demoDiagnostic(device)})});
 const conds=Object.values(Condition);
 const set=(k:keyof DeviceInput,v:unknown)=>setFlow({...flow,device:{...device,[k]:v}});
 return <div className="page-wrap"><PageHead kicker="STEP 02 · CONDITION" title="What shape is it in?" desc="Tell us what you can observe. These diagnostics use your answers and simulated checks—not access to device hardware."/>
 <div className="grid-main"><div className="panel" style={{padding:24}}><div className="flex justify-between"><div><div className="eyebrow">DEVICE CONDITION</div><h3 style={{margin:'7px 0 18px',fontSize:17}}>{device.brand||device.category} {device.model}</h3></div><SourceTag>{device.source||DeviceInputSource.USER_REPORTED}</SourceTag></div>
 <label><span className="label">How would you describe its overall condition?</span><select className="field" value={device.condition} onChange={e=>set('condition',e.target.value)}>{conds.map(c=><option key={c} value={c}>{c.replaceAll('_',' ')}</option>)}</select></label>
 <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:14}}><label><span className="label">Does it power on?</span><select className="field" value={String(device.powersOn)} onChange={e=>set('powersOn',e.target.value==='true')}><option value="true">Yes</option><option value="false">No</option></select></label><label><span className="label">Battery health (if known)</span><input className="field" type="number" min="0" max="100" value={device.batteryHealth??''} placeholder="e.g. 78%" onChange={e=>set('batteryHealth',Number(e.target.value))}/></label><label><span className="label">Screen condition</span><select className="field" value={device.screenCondition||''} onChange={e=>set('screenCondition',e.target.value)}><option value="">Choose</option><option>Intact</option><option>Cracked</option><option>Not working</option><option>Unknown</option></select></label><label><span className="label">Physical damage</span><input className="field" value={device.physicalDamage||''} onChange={e=>set('physicalDamage',e.target.value)} placeholder="Describe visible damage"/></label></div>
 <div style={{marginTop:15}}><label className="flex items-center gap-3" style={{fontSize:12,fontWeight:700}}><input type="checkbox" checked={device.hasPersonalData??true} onChange={e=>set('hasPersonalData',e.target.checked)}/> This device may contain personal data</label></div>
 <Button className="btn-primary" onClick={start} disabled={run.isPending} style={{width:'100%',marginTop:20}} data-testid="button-run-diagnostics">{run.isPending?'Assessing…':'Assess condition'} <ArrowRight size={16}/></Button>
 {run.error&&<Notice>Showing a labeled simulated diagnostic because the demo assessment service is unavailable.</Notice>}
 {flow.diagnostics&&<div style={{marginTop:17}}><Notice><b>Overall: {flow.diagnostics.overallCondition}</b> · {flow.diagnostics.overallScore}/100 · {Math.round(flow.diagnostics.confidence*100)}% confidence <SourceTag>SIMULATED</SourceTag><div style={{marginTop:6}}>{flow.diagnostics.recommendedAction}</div></Notice><div style={{marginTop:12,display:'grid',gap:8}}>{flow.diagnostics.tests.map((test,index)=><div key={`${test.name}-${index}`} style={{padding:'13px 14px',border:'1px solid hsl(var(--border))',borderRadius:13,display:'grid',gridTemplateColumns:'1fr auto',gap:6,alignItems:'center'}}><b style={{fontSize:12}}>{test.name}</b><span className="badge outline">{test.status} · {test.score}/100</span><span style={{fontSize:10,color:'hsl(var(--muted-foreground))',lineHeight:1.5}}>{test.explanation}</span><SourceTag>{test.source}</SourceTag></div>)}</div></div>}
 </div><div style={{display:'grid',gap:15}}><div className="panel" style={{padding:22}}><div className="eyebrow">WHAT WE CAN AND CAN’T CHECK</div><div style={{display:'grid',gap:13,marginTop:16}}>{[['Reported by you','Power, visible damage, screen observations'],['Estimated','Possible condition and value ranges'],['Simulated','Checks that would normally need access to hardware']].map(([a,b])=><div key={a} className="flex gap-3"><div style={{width:8,height:8,borderRadius:99,background:a==='Reported by you'?'#78925f':a==='Estimated'?'#d99470':'#7e9690',marginTop:5}}/><div><b style={{fontSize:12}}>{a}</b><div style={{fontSize:10,color:'hsl(var(--muted-foreground))',marginTop:3}}>{b}</div></div></div>)}</div><p style={{fontSize:10,color:'hsl(var(--muted-foreground))',lineHeight:1.65,borderTop:'1px solid hsl(var(--border))',paddingTop:12,marginBottom:0}}>No browser hardware checks are performed. A simulated result cannot verify a device’s actual condition.</p></div><DemoJourneys/></div></div>
 </div>;
}
function demoDiagnostic(d:DeviceInput):DiagnosticResult{return {overallCondition:d.condition,overallScore:d.condition==='REPAIRABLE'?73:d.powersOn?82:19,confidence:.76,tests:[{name:'Power status',status:d.powersOn?'PASS':'FAIL',score:d.powersOn?90:10,source:'USER_REPORTED',explanation:d.powersOn?'Device powers on per your answer.':'Device does not power on per your answer.',recommendation:d.powersOn?'Continue to assess other components.':'Seek responsible recycling or repair assessment.'},{name:'Screen condition',status:d.screenCondition==='Cracked'?'WARNING':'PASS',score:d.screenCondition==='Cracked'?42:80,source:'USER_REPORTED',explanation:`Screen condition: ${d.screenCondition||'not reported'}.`,recommendation:'Confirm screen condition in person.'},{name:'Battery',status:'WARNING',score:d.batteryHealth??55,source:'SIMULATED',explanation:'Battery status is a simulated assessment.',recommendation:'A qualified partner can verify battery health.'}],recommendedAction:d.condition==='WORKING'||d.condition==='REPAIRABLE'?'Resale is the recommended route.':'Recycling is the recommended route.'}}

function ValuationPage(){
 const{flow,setFlow}=useContext(FlowContext);const device=useCurrentDevice();const calc=useCalculateEcoCycleValuation();
 const estimate=()=>calc.mutate({data:{device}},{onSuccess:value=>setFlow({...flow,device,value}),onError:()=>setFlow({...flow,device,value:demoValue(device)})});
 const v=flow.value;
 return <div className="page-wrap"><PageHead kicker="STEP 03 · VALUE" title="Understand the possible value." desc="A directional estimate based on the details you shared. A final offer can only be made after in-person inspection."/>
 <div className="grid-main"><div className="panel" style={{padding:25}}><div className="flex items-center justify-between"><div><div className="eyebrow">ESTIMATE INPUT</div><h3 style={{margin:'8px 0',fontSize:17}}>{device.brand||device.category} {device.model||''}</h3></div><SourceTag>{device.source||'USER_REPORTED'}</SourceTag></div><div className="rule-box" style={{margin:'14px 0 18px'}}><b style={{fontSize:12}}>Condition: {device.condition}</b><p style={{fontSize:11,margin:'5px 0 0',color:'hsl(var(--muted-foreground))'}}>Estimates change with actual condition, demand, and local inspection.</p></div><Button className="btn-primary" style={{width:'100%'}} disabled={calc.isPending} onClick={estimate} data-testid="button-calculate-value">{calc.isPending?'Preparing estimate…':'Calculate indicative value'} <ArrowRight size={16}/></Button>
 {calc.error&&<Notice>Estimate service unavailable; showing a local simulated range for this demo.</Notice>}
 {v&&<div style={{marginTop:20}}><div className="eyebrow">ESTIMATED VALUES · INR</div><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:9,marginTop:10}}>{[['Resale',v.resaleValue],['Trade-in',v.tradeInValue],['Scrap',v.scrapValue]].map(([n,val])=><div key={n as string} style={{padding:13,borderRadius:14,background:'hsl(var(--secondary))'}}><div className="eyebrow">{n as string}</div><b className="mono" style={{fontSize:17,display:'block',marginTop:7}}>₹{Number(val).toLocaleString('en-IN')}</b></div>)}</div><p style={{fontSize:10,color:'hsl(var(--muted-foreground))',lineHeight:1.7}}>Confidence estimate: {Math.round(v.confidence*100)}% · not a guaranteed quote.</p><ul style={{paddingLeft:18,fontSize:11,lineHeight:1.8}}>{v.assumptions.map(a=><li key={a}>{a}</li>)}</ul></div>}
 </div><div style={{display:'grid',gap:15}}><div className="panel" style={{padding:22}}><div className="flex items-center gap-2"><Sparkles size={17}/><b style={{fontSize:13}}>How to read an estimate</b></div><p style={{fontSize:11,lineHeight:1.8,color:'hsl(var(--muted-foreground))'}}>These are indicative values in INR, generated from user-reported details and market assumptions. They are not quotes, trade-in offers, or promises of payment.</p><SourceTag>ESTIMATED</SourceTag></div><div className="panel" style={{padding:22}}><div className="eyebrow">THE ROUTE STILL FOLLOWS CONDITION</div><h3 className="serif" style={{fontSize:25,margin:'12px 0'}}>A higher scrap value<br/>doesn’t make it resale.</h3><p style={{fontSize:11,lineHeight:1.7,color:'hsl(var(--muted-foreground))'}}>Working or repairable devices are routed to resale. Non-working, dead, and scrap devices go to recycling.</p></div></div></div></div>;
}
function demoValue(d:DeviceInput):Valuation {const working=d.condition==='WORKING'||d.condition==='REPAIRABLE';const base=d.category==='Laptop'?12400:d.category==='Smartphone'?9200:4800;return {currency:'INR',resaleValue:working?base:0,tradeInValue:working?Math.round(base*.72):0,scrapValue:working?Math.round(base*.09):Math.round(base*.11),valueDifference:working?Math.round(base*.91):0,confidence:.68,assumptions:['Based on user-reported model, age and condition.','Local demand and in-person inspection may change value.','Illustrative demo estimate; not a guaranteed quote.']}}
function SanitizationPage(){
 const{flow,setFlow}=useContext(FlowContext);const device=useCurrentDevice();const start=useStartEcoCycleSanitization();const makeCert=useCreateEcoCycleCertificate();
 const[method,setMethod]=useState('Cryptographic erase');const[storage,setStorage]=useState('SSD');const[name,setName]=useState(`${device.brand||device.category} ${device.model||''}`.trim());const[done,setDone]=useState<SanitizationRecord|null>(flow.sanitation??null);
 const execute=()=>start.mutate({data:{deviceName:name||device.category,deviceIdentifier:device.model||undefined,storageType:storage,method}},{onSuccess:r=>{setFlow({...flow,device,sanitation:r});setDone(r);makeCert.mutate({data:{record:r}})},onError:()=>{const r:SanitizationRecord={id:`local-${Date.now()}`,certificateId:`DEMO-${Date.now().toString().slice(-6)}`,deviceName:name||device.category,deviceIdentifier:device.model,method,standard:'Simulated workflow',status:'DEMO SIMULATION',verificationStatus:'NOT VERIFIED',timestamp:new Date().toISOString(),certificateHash:'Not cryptographically verified'};setFlow({...flow,device,sanitation:r});setDone(r)}});
 return <div className="page-wrap"><PageHead kicker="STEP 04 · PERSONAL DATA" title="Keep your data yours." desc="Prepare your device before it changes hands. This is guidance and a recorded simulation—not a real device wipe."/>
 <div className="grid-main"><div className="panel" style={{padding:25}}><div style={{display:'flex',gap:13,alignItems:'center',marginBottom:18}}><div style={{width:46,height:46,borderRadius:15,background:'hsl(var(--secondary))',display:'grid',placeItems:'center'}}><LockKeyhole size={21}/></div><div><div className="eyebrow">SIMULATED SANITIZATION</div><b>{name||device.category}</b></div></div>
 <Notice tone="coral"><b>Important limitation:</b> EcoCycle AI cannot access, erase, or verify data on your device. This demo only records a simulated sanitization workflow. Use the manufacturer’s official reset instructions or a qualified service provider before handing over your device.</Notice>
 <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12,marginTop:18}}><label><span className="label">Device name</span><input className="field" value={name} onChange={e=>setName(e.target.value)}/></label><label><span className="label">Storage type</span><select className="field" value={storage} onChange={e=>setStorage(e.target.value)}><option>SSD</option><option>HDD</option><option>Flash storage</option><option>Unknown</option></select></label></div>
 <label style={{display:'block',marginTop:13}}><span className="label">Method to record</span><select className="field" value={method} onChange={e=>setMethod(e.target.value)}><option>Cryptographic erase</option><option>Secure overwrite</option><option>Manufacturer factory reset</option><option>Physical destruction (qualified provider)</option></select></label>
 <Button className="btn-primary" style={{width:'100%',marginTop:19}} onClick={execute} disabled={start.isPending} data-testid="button-simulate-sanitization">{start.isPending?'Recording simulation…':'Record a simulated sanitization'} <ArrowRight size={16}/></Button>
 {done&&<div style={{marginTop:18}}><Notice><b>Simulation recorded</b> · {done.certificateId}<div style={{marginTop:5}}>Verification: {done.verificationStatus}. No data was erased or verified.</div></Notice><div className="flex gap-2" style={{marginTop:12}}><Link className="btn btn-soft" href="/certificates" data-testid="link-view-certificates">View certificates <FileCheck2 size={15}/></Link></div></div>}
 </div><div className="panel" style={{padding:23}}><div className="eyebrow">BEFORE YOU PASS IT ON</div><h3 className="serif" style={{fontSize:27,margin:'12px 0 17px'}}>Your practical checklist</h3>{['Back up anything you want to keep.','Sign out of accounts and remove device locks.','Use the manufacturer’s reset process.','Remove SIM and memory cards.','Keep proof of handover from your chosen partner.'].map((item,i)=><div key={item} className="flex gap-3" style={{padding:'12px 0',borderTop:'1px solid hsl(var(--border))'}}><span className="badge" style={{width:25,height:25,justifyContent:'center',padding:0}}>{i+1}</span><span style={{fontSize:12,lineHeight:1.55}}>{item}</span></div>)}</div></div>
 </div>;
}
function useRouting(){
 const {flow,setFlow}=useContext(FlowContext);const device=useCurrentDevice();const route=useEvaluateEcoCycleRouting();
 const recommend=()=>route.mutate({data:{condition:device.condition,deviceName:`${device.brand||device.category} ${device.model||''}`.trim()}},{onSuccess:r=>setFlow({...flow,device,routing:r}),onError:()=>setFlow({...flow,device,routing:{route:device.condition==='WORKING'||device.condition==='REPAIRABLE'?EcoRoute.RESALE:EcoRoute.RECYCLING,condition:device.condition,reason:'Recommended route follows the condition rule; this is local demo guidance.',nextSteps:['Confirm actual condition in person.','Choose a responsible destination.']}})});
 return {device,flow,setFlow,recommend,pending:route.isPending,error:route.isError};
}
function Results(){
 const{device,flow,recommend,pending,error}=useRouting();const r=flow.routing;const resale=device.condition==='WORKING'||device.condition==='REPAIRABLE';const route=r?.route??(resale?EcoRoute.RESALE:EcoRoute.RECYCLING);
 return <div className="page-wrap"><PageHead kicker="STEP 05 · NEXT DESTINATION" title="A better next, made clearer." desc="Our recommendation uses the condition you reported. The final destination depends on an in-person assessment."/>
 {error&&<Notice>Showing a local simulated recommendation because the demo service is unavailable.</Notice>}
 {!r&&<div className="panel" style={{padding:24,marginBottom:18}}><div className="eyebrow">CONDITION ON FILE · {device.condition}</div><p style={{fontSize:12,color:'hsl(var(--muted-foreground))'}}>Get the recommendation for {device.brand||device.category} {device.model}.</p><Button className="btn-primary" onClick={recommend} disabled={pending} data-testid="button-get-recommendation">{pending?'Preparing recommendation…':'Get my recommendation'} <ArrowRight size={16}/></Button></div>}
 <div className="panel" style={{padding:'clamp(24px,5vw,46px)',background:'hsl(var(--sidebar))',color:'#f2f0df',position:'relative',overflow:'hidden'}}><div style={{position:'absolute',right:-30,bottom:-90,width:270,height:270,borderRadius:'50%',border:'1px solid rgba(212,226,155,.2)'}}/><div style={{position:'relative',zIndex:1}}><div className="eyebrow" style={{color:'#cbd9a0'}}>PERSONAL CIRCULAR ROUTE · {device.condition}</div><div className="serif" style={{fontSize:'clamp(48px,8vw,90px)',lineHeight:.96,letterSpacing:'-.055em',margin:'21px 0'}}>{route===EcoRoute.RESALE?'Resale':'Recycling'}<span style={{color:'#d2e09e'}}>.</span></div><p style={{fontSize:13,lineHeight:1.8,maxWidth:560,color:'rgba(242,240,223,.7)'}}>{r?.reason??(resale?'This device is reported as working or repairable. The recommended next route is resale.':'This device is reported as non-working, dead, or scrap. The recommended next route is responsible recycling.')}</p>
 <div style={{display:'inline-flex',padding:'10px 14px',borderRadius:11,background:'rgba(255,255,255,.1)',fontSize:11,fontWeight:800,marginTop:8}}>RULE: WORKING / REPAIRABLE → RESALE <span style={{margin:'0 8px',opacity:.45}}>|</span> NON-WORKING / DEAD / SCRAP → RECYCLING</div>
 <div style={{display:'flex',gap:10,flexWrap:'wrap',marginTop:25}}><Link href="/matchmaker" className="btn" style={{background:'#d4e29b',color:'#1a3c32'}} data-testid="link-find-destination">Find a destination <ArrowRight size={16}/></Link><Link href="/sanitization" className="btn" style={{border:'1px solid rgba(255,255,255,.24)',color:'#f2f0df'}} data-testid="link-data-protection">Review data protection <LockKeyhole size={15}/></Link></div>
 </div></div>
 <div className="grid-main" style={{marginTop:18}}><div className="panel" style={{padding:22}}><div className="eyebrow">NEXT STEPS</div>{(r?.nextSteps??(resale?['Check the item’s condition with a resale partner.','Review indicative estimates; they are not guaranteed quotes.','Protect personal data before handover.']:['Find a verified recycling partner near you.','Ask what materials and proof of processing they provide.','Protect personal data before handover.'])).map((s,i)=><div key={s} className="flex gap-3" style={{padding:'13px 0',borderBottom:'1px solid hsl(var(--border))'}}><Check size={16} color="hsl(var(--primary))"/><span style={{fontSize:12}}>{s}</span></div>)}</div><div className="panel" style={{padding:22}}><div className="eyebrow">YOUR DEVICE</div><h3 className="serif" style={{fontSize:25,margin:'9px 0'}}>{device.brand||device.category} {device.model}</h3><SourceTag>{device.source||'USER_REPORTED'}</SourceTag><p style={{fontSize:11,color:'hsl(var(--muted-foreground))',lineHeight:1.7}}>Recommendation based on {device.condition.toLowerCase().replaceAll('_',' ')} condition. Verify with your chosen destination.</p>{flow.value&&<div className="rule-box"><div className="eyebrow">INDICATIVE ESTIMATED RESALE</div><b className="mono" style={{fontSize:20}}>₹{flow.value.resaleValue.toLocaleString('en-IN')}</b><div style={{fontSize:10}}>Not a guaranteed quote</div></div>}</div></div>
 </div>;
}
function PartnerFinder(){
 const {flow}=useContext(FlowContext);const condition=flow.device?.condition??Condition.WORKING;const route=condition==='WORKING'||condition==='REPAIRABLE'?EcoRoute.RESALE:EcoRoute.RECYCLING;
 const q=useListEcoCyclePartners({route},{query:{queryKey:getListEcoCyclePartnersQueryKey({route})}});
 return <div className="page-wrap"><PageHead kicker="RESPONSIBLE DESTINATIONS" title="Find a good next home." desc={`Demo-backed partners for the ${route.toLowerCase()} route. Verify acceptance, fees, and handover details directly before visiting.`}/>
 <div className="rule-box flex justify-between items-center" style={{marginBottom:17,gap:12}}><div><div className="eyebrow">FILTERED BY THE CONDITION RULE</div><b>{condition} → {route}</b></div><span className={`badge ${route===EcoRoute.RECYCLING?'coral':''}`}>{route}</span></div>
 {q.isLoading?<LoadingPanel/>:q.isError?<ErrorPanel onRetry={()=>q.refetch()}/>:q.data?.length?<div style={{display:'grid',gridTemplateColumns:'repeat(2,minmax(0,1fr))',gap:14}}>{q.data.map(p=><article key={p.id} className="panel" style={{padding:22}}><div className="flex justify-between items-start gap-3"><div><span className="eyebrow">{p.type}</span><h3 style={{fontSize:17,letterSpacing:'-.04em',margin:'7px 0 5px'}}>{p.name}</h3></div>{p.verified?<span className="badge"><BadgeCheck size={13}/> Verified listing</span>:<span className="badge outline">Unverified</span>}</div><p style={{fontSize:11,color:'hsl(var(--muted-foreground))',lineHeight:1.6}}>{p.address}</p><div className="flex justify-between items-center" style={{paddingTop:12,borderTop:'1px solid hsl(var(--border))'}}><span className="mono" style={{fontSize:11}}>{p.distanceKm} km away</span><span className="badge outline">{p.demo?'DEMO LISTING':'PARTNER LISTING'}</span></div><p style={{fontSize:10,lineHeight:1.6}}>Accepts: {p.acceptedCategories.join(', ')}</p><Notice>Confirm availability, acceptance criteria, and all charges directly with this destination.</Notice></article>)}</div>:<div className="panel"><EmptyBlock title="No demo partners found for this route" detail="Try again later or check the route shown above. Partner listings in this experience are demo-backed."/></div>}
 </div>;
}
function ImpactPage(){
 const i=useGetEcoCycleImpact({query:{queryKey:getGetEcoCycleImpactQueryKey()}});const c=useGetEcoCycleCredits({query:{queryKey:getGetEcoCycleCreditsQueryKey()}});
 return <div className="page-wrap"><PageHead kicker="IMPACT, WITH CONTEXT" title="A small choice adds up." desc="Environmental impact and eco credits shown here are demo summaries, not a personal verified measurement."/>
 {i.isLoading||c.isLoading?<LoadingPanel/>:i.isError||c.isError?<ErrorPanel onRetry={()=>{i.refetch();c.refetch()}}/>:<><div className="grid-main"><div className="panel" style={{padding:26,background:'hsl(var(--sidebar))',color:'#f2f0df'}}><div className="eyebrow" style={{color:'#cbd9a0'}}>DEMO IMPACT SUMMARY</div><div className="serif" style={{fontSize:62,letterSpacing:'-.06em',marginTop:17}}>{i.data?.co2SavedKg??0}<small style={{fontSize:19}}> kg</small></div><span style={{fontSize:12,color:'rgba(242,240,223,.64)'}}>estimated CO₂ saved</span><div className="eyebrow" style={{color:'rgba(242,240,223,.48)',marginTop:22}}>SOURCE · {i.data?.source??'DEMO DATA'} · {Math.round((i.data?.confidence??0)*100)}% confidence</div></div>
 <div className="panel" style={{padding:25}}><div className="eyebrow">ECO CREDITS · DEMO WALLET</div><div className="serif" style={{fontSize:55,margin:'13px 0 4px'}}> {c.data?.balance??0}</div><span style={{fontSize:11,color:'hsl(var(--muted-foreground))'}}>Credits are illustrative in this demo. No monetary value implied.</span><Link href="/history" className="btn btn-soft" style={{marginTop:20}} data-testid="link-credit-history">View activity <ArrowRight size={15}/></Link></div></div>
 <div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',gap:12,marginTop:15}}>{[['Devices processed',i.data?.devicesProcessed],['Devices reused',i.data?.devicesReused],['Devices recycled',i.data?.devicesRecycled],['Material recovered',`${i.data?.materialRecoveredKg??0} kg`]].map(([a,b])=><div className="panel stat-card" key={a as string}><div className="eyebrow">{a as string}</div><strong>{b??0}</strong><SourceTag>DEMO DATA</SourceTag></div>)}</div>
 <div className="panel" style={{padding:22,marginTop:15}}><div className="flex gap-3"><Leaf size={20} color="hsl(var(--primary))"/><div><b style={{fontSize:13}}>Impact is estimated, not a receipt.</b><p style={{fontSize:11,color:'hsl(var(--muted-foreground))',lineHeight:1.7,marginBottom:0}}>CO₂, materials recovered, and landfill diversion use demo methodology and summary data. They are not a verified lifecycle analysis of your individual device.</p></div></div></div>
 </>}
 </div>;
}
function CertificatesPage(){
 const q=useListEcoCycleCertificates({query:{queryKey:getListEcoCycleCertificatesQueryKey()}});const{flow}=useContext(FlowContext);
 return <div className="page-wrap"><PageHead kicker="YOUR RECORDS" title="Sanitization certificates." desc="Certificates document the workflow that was recorded. This demo cannot prove that a physical device was wiped."/>
 <Notice tone="coral"><b>Simulated only.</b> A certificate from this demo is not evidence of actual sanitization or verification.</Notice>
 <div style={{marginTop:17}}>{flow.sanitation&&<div className="panel" style={{padding:20,marginBottom:12,display:'flex',gap:14,alignItems:'center'}}><div style={{width:44,height:44,borderRadius:14,background:'hsl(var(--secondary))',display:'grid',placeItems:'center'}}><FileCheck2/></div><div style={{flex:1}}><div className="eyebrow">{flow.sanitation.certificateId} · LOCAL SIMULATION</div><b style={{fontSize:13,display:'block',marginTop:5}}>{flow.sanitation.deviceName}</b><div style={{fontSize:10,color:'hsl(var(--muted-foreground))',marginTop:4}}>{flow.sanitation.method} · {flow.sanitation.verificationStatus}</div></div><span className="badge coral">NOT VERIFIED</span></div>}{q.isLoading?<LoadingPanel/>:q.isError?<ErrorPanel onRetry={()=>q.refetch()}/>:q.data?.length?<div style={{display:'grid',gap:12}}>{q.data.map(c=><div className="panel" key={c.id} style={{padding:20,display:'flex',gap:14,alignItems:'center'}}><div style={{width:44,height:44,borderRadius:14,background:'hsl(var(--secondary))',display:'grid',placeItems:'center'}}><FileCheck2/></div><div style={{flex:1}}><div className="eyebrow">{c.certificateId} · {c.verificationStatus}</div><b style={{fontSize:13,display:'block',marginTop:5}}>{c.deviceName}</b><div style={{fontSize:10,color:'hsl(var(--muted-foreground))',marginTop:4}}>{c.method} · {new Date(c.timestamp).toLocaleString()}</div></div><span className="badge outline">{c.status}</span></div>)}</div>:<div className="panel"><EmptyBlock title={flow.sanitation?'No other certificates in the demo service':'No certificates yet'} detail="A workflow record appears here after you record a sanitization simulation." action={<Link href="/sanitization" className="btn btn-soft" data-testid="link-start-sanitization">Go to data protection <ArrowRight size={15}/></Link>}/></div>}</div>
 </div>;
}
function HistoryPage(){
 const q=useListEcoCycleHistory({query:{queryKey:getListEcoCycleHistoryQueryKey()}});const devices=useListEcoCycleDevices({query:{queryKey:getListEcoCycleDevicesQueryKey()}});
 const remove=useDeleteEcoCycleDevice();const qc=useQueryClient();
 const removeRow=(id:string)=>{if(window.confirm('Remove this demo assessment?'))remove.mutate({deviceId:id},{onSuccess:()=>qc.invalidateQueries({queryKey:getListEcoCycleDevicesQueryKey()})})};
 const rows=q.data??[];
 return <div className="page-wrap"><PageHead kicker="YOUR ASSESSMENTS" title="A record of what’s next." desc="The service provides demo-backed history. Saved visitor workflow details are kept locally only for this session." action={<Link href="/scan" className="btn btn-primary" data-testid="link-history-assess">New assessment <ArrowRight size={15}/></Link>}/>
 {q.isLoading||devices.isLoading?<LoadingPanel/>:q.isError||devices.isError?<ErrorPanel onRetry={()=>{q.refetch();devices.refetch()}}/>:rows.length||devices.data?.length?<div className="panel" style={{padding:20,overflowX:'auto'}}><div style={{minWidth:620}}><div style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr 40px',gap:12,padding:'9px 8px',borderBottom:'1px solid hsl(var(--border))'}} className="eyebrow"><span>DEVICE</span><span>CONDITION</span><span>ROUTE</span><span>DATE</span><span/></div>{rows.map((r:any)=><div key={r.id} style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr 40px',gap:12,padding:'15px 8px',borderBottom:'1px solid hsl(var(--border))',fontSize:11,alignItems:'center'}}><b>{r.deviceName}</b><span>{r.condition}</span><span className="badge">{r.route}</span><span>{r.date}</span><span/></div>)}{devices.data?.map(d=><div key={d.id} style={{display:'grid',gridTemplateColumns:'2fr 1fr 1fr 1fr 40px',gap:12,padding:'15px 8px',borderBottom:'1px solid hsl(var(--border))',fontSize:11,alignItems:'center'}}><div><b>{d.brand} {d.model||d.category}</b><div style={{marginTop:5}}><SourceTag>{d.source}</SourceTag></div></div><span>{d.condition}</span><span>Pending</span><span>{new Date(d.createdAt).toLocaleDateString()}</span><button onClick={()=>removeRow(d.id)} aria-label={`Delete ${d.brand||d.category}`} data-testid={`delete-device-${d.id}`} style={{border:0,background:'transparent',cursor:'pointer',color:'hsl(var(--muted-foreground))'}}><Trash2 size={15}/></button></div>)}</div></div>:<div className="panel"><EmptyBlock title="Your history is ready to begin" detail="Once you assess and save a device, its journey can appear here." action={<Link href="/scan" className="btn btn-primary" data-testid="link-start-history">Assess your first device <ArrowRight size={15}/></Link>}/></div>}
 {remove.isPending&&<p className="eyebrow">Removing assessment…</p>}</div>;
}
function ProfilePage(){
 const[stored,setStored]=useState(()=>localStorage.getItem('ecocycle-profile-name')||'Guest visitor');const[edit,setEdit]=useState(stored);const[saved,setSaved]=useState(false);
 const save=(e:FormEvent)=>{e.preventDefault();localStorage.setItem('ecocycle-profile-name',edit);setStored(edit);setSaved(true)};
 return <div className="page-wrap"><PageHead kicker="YOUR PREFERENCES" title="Profile & settings." desc="This is a demo account. These preferences stay in this browser and are not connected to an authenticated profile."/>
 <div className="grid-main"><form className="panel" style={{padding:24}} onSubmit={save}><div className="eyebrow">VISITOR PROFILE · LOCAL ONLY</div><label style={{display:'block',marginTop:18}}><span className="label">Name shown in this browser</span><input className="field" value={edit} onChange={e=>setEdit(e.target.value)} data-testid="input-profile-name"/></label><label style={{display:'block',marginTop:14}}><span className="label">Preferred city</span><select className="field" defaultValue="Bengaluru"><option>Bengaluru</option><option>Mumbai</option><option>Delhi</option><option>Chennai</option><option>Hyderabad</option><option>Pune</option></select></label><Button type="submit" className="btn-primary" style={{marginTop:18}} data-testid="button-save-profile">Save local preferences <Check size={15}/></Button>{saved&&<div role="status" style={{fontSize:11,marginTop:12,color:'hsl(var(--primary))'}}>Saved in this browser.</div>}</form>
 <div style={{display:'grid',gap:14}}><div className="panel" style={{padding:22}}><div className="flex items-center gap-3"><div style={{width:40,height:40,borderRadius:14,background:'hsl(var(--secondary))',display:'grid',placeItems:'center'}}><ShieldCheck size={18}/></div><div><b style={{fontSize:13}}>Privacy by clarity</b><div style={{fontSize:10,color:'hsl(var(--muted-foreground))',marginTop:4}}>No account sign-in is required in this demo.</div></div></div></div><div className="panel" style={{padding:22}}><div className="eyebrow">INFORMATION LABELS</div>{[['User-reported','What you tell us'],['Estimated','Model-based guidance, never a quote'],['Simulated','A demonstration, not real device verification'],['Demo data','Shared service summary or sample listing']].map(([a,b])=><div key={a} style={{display:'flex',justifyContent:'space-between',gap:8,padding:'11px 0',borderBottom:'1px solid hsl(var(--border))',fontSize:10}}><b>{a}</b><span style={{textAlign:'right',color:'hsl(var(--muted-foreground))'}}>{b}</span></div>)}</div></div></div></div>;
}
function AuthPage({register=false}:{register?:boolean}){
 const[,go]=useLocation();const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[name,setName]=useState('');const[message,setMessage]=useState('');
 const submit=(e:FormEvent)=>{e.preventDefault();if(register&&name.trim().length<2){setMessage('Please enter a name of at least two characters.');return}if(!email.includes('@')){setMessage('Enter a valid email address.');return}if(password.length<6){setMessage('Use at least six characters for this demo password.');return}localStorage.setItem('ecocycle-demo-session',email);if(name)localStorage.setItem('ecocycle-profile-name',name);setMessage('Demo access is ready. Taking you to your overview…');setTimeout(()=>go('/dashboard'),450)};
 return <div style={{minHeight:'100dvh',display:'grid',gridTemplateColumns:'1.05fr .95fr'}} className="auth-grid">
 <div style={{background:'hsl(var(--sidebar))',color:'#f2f0df',padding:'clamp(30px,7vw,90px)',display:'flex',flexDirection:'column',justifyContent:'space-between',minHeight:'100dvh'}}><Link href="/" className="flex items-center gap-3"><Mark/><b>EcoCycle <span style={{color:'#d4e29b'}}>AI</span></b></Link><div><div className="eyebrow" style={{color:'#d4e29b'}}>A DEMO ACCOUNT, NOT A REAL ONE</div><h1 className="serif" style={{fontSize:'clamp(47px,6vw,78px)',lineHeight:.96,letterSpacing:'-.055em',margin:'20px 0'}}>Good decisions<br/>start with<br/><i>good context.</i></h1><p style={{fontSize:13,lineHeight:1.8,color:'rgba(242,240,223,.66)',maxWidth:380}}>Use a local demo profile to explore a device’s possible next life. Shared service data is demo-backed and not user-specific.</p></div><span className="eyebrow" style={{color:'rgba(242,240,223,.48)'}}>INDIA · CIRCULAR ECONOMY, MADE PERSONAL</span></div>
 <div style={{padding:'30px clamp(22px,7vw,90px)',display:'flex',alignItems:'center',justifyContent:'center'}}><div style={{width:'100%',maxWidth:390}}><Link href="/" className="eyebrow flex items-center gap-2" data-testid="link-back-home"><ArrowLeft size={14}/> BACK TO ECOCYCLE</Link><h2 className="serif" style={{fontSize:39,letterSpacing:'-.05em',margin:'27px 0 6px'}}>{register?'Create a demo profile':'Welcome back.'}</h2><p style={{fontSize:12,color:'hsl(var(--muted-foreground))',lineHeight:1.7}}>{register?'No real account will be created. Your demo details stay in this browser.':'Demo access only. There is no password-backed account in this experience.'}</p><form onSubmit={submit} style={{marginTop:26,display:'grid',gap:15}}>{register&&<label><span className="label">Your name</span><input className="field" value={name} onChange={e=>setName(e.target.value)} placeholder="Name" required data-testid="input-register-name"/></label>}<label><span className="label">Email address</span><input type="email" className="field" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required data-testid="input-auth-email"/></label><label><span className="label">Demo password</span><input type="password" className="field" value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters" required data-testid="input-auth-password"/></label><Button type="submit" className="btn-primary" style={{width:'100%',marginTop:4}} data-testid="button-auth-submit">{register?'Create demo profile':'Continue to demo'} <ArrowRight size={16}/></Button></form>{message&&<div role="status" style={{fontSize:11,marginTop:13,lineHeight:1.6}}>{message}</div>}<Notice><b>Demo mode.</b> Do not use a real password. No authentication service is connected.</Notice><p style={{fontSize:11,marginTop:19,color:'hsl(var(--muted-foreground))'}}>{register?'Already exploring?':'New here?'} <Link href={register?'/login':'/register'} style={{color:'hsl(var(--primary))',fontWeight:800}} data-testid={register?'link-to-login':'link-to-register'}>{register?'Log in':'Create a demo profile'}</Link></p></div></div>
 <style>{`@media(max-width:740px){.auth-grid{grid-template-columns:1fr!important}.auth-grid>div:first-child{min-height:auto!important;padding:24px!important}.auth-grid>div:first-child>div:nth-child(2){margin:38px 0}.auth-grid>div:first-child h1{font-size:49px!important}.auth-grid>div:nth-child(2){padding:35px 22px!important}}`}</style>
 </div>;
}
function HealthStatus(){
 const q=useHealthCheck({query:{queryKey:getHealthCheckQueryKey(),retry:false}});
 return <span title="Service status" className="badge outline" style={{fontSize:9}}><span style={{width:6,height:6,borderRadius:9,background:q.isError?'#ce745c':q.isLoading?'#c2ad73':'#76925d'}}/>{q.isError?'SERVICE UNAVAILABLE':q.isLoading?'CONNECTING':`SERVICE ${q.data?.status??'READY'}`}</span>;
}
function AppShell({children}:{children:ReactNode}){return <Shell>{children}</Shell>}
function Router(){
 const[loc]=useLocation();const[flow,setFlow]=useState<Workflow>({device:null});const[device,setDevice]=useState<DeviceInput>(blankDevice);
 const value=useMemo(()=>({flow,setFlow,device,setDevice}),[flow,device]);
 const publicRoutes=loc==='/'||loc==='/login'||loc==='/register';
 return <FlowContext.Provider value={value}>{publicRoutes?<Switch><Route path="/" component={Landing}/><Route path="/login"><AuthPage/></Route><Route path="/register"><AuthPage register/></Route><Route component={NotFound}/></Switch>:<AppShell><Switch>
   <Route path="/dashboard" component={Dashboard}/><Route path="/scan" component={ScanPage}/><Route path="/diagnostics" component={Diagnostics}/>
   <Route path="/valuation" component={ValuationPage}/><Route path="/sanitization" component={SanitizationPage}/><Route path="/results" component={Results}/>
   <Route path="/matchmaker" component={PartnerFinder}/><Route path="/impact" component={ImpactPage}/><Route path="/certificates" component={CertificatesPage}/>
   <Route path="/history" component={HistoryPage}/><Route path="/profile" component={ProfilePage}/><Route component={NotFound}/>
 </Switch></AppShell>}</FlowContext.Provider>;
}
function App(){
 return <QueryClientProvider client={queryClient}><TooltipProvider><WouterRouter base={import.meta.env.BASE_URL.replace(/\/$/,'')}><RoutedErrorBoundary><Router/></RoutedErrorBoundary></WouterRouter><Toaster/></TooltipProvider></QueryClientProvider>;
}
function RoutedErrorBoundary({children}:{children:ReactNode}){const[location]=useLocation();return <ErrorBoundary resetKey={location}>{children}</ErrorBoundary>}
export default App;
